INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
WARNING:django.request:Not Found: /mpesa/confitm
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\urls.py changed, reloading.
WARNING:django.request:Method Not Allowed: /mpesa/submit/
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\models.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 136, in stk_push
    if account_number:
       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'account_number' where it is not associated with a value
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'WSGIRequest'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 162, in stk_push
    transaction = PaymentTransaction.objects.filter(id=transaction_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\lookups.py", line 364, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <WSGIRequest: GET '/items/stk_push'>.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2117, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'WSGIRequest'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 162, in stk_push
    transaction = PaymentTransaction.objects.filter(id=transaction_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\lookups.py", line 364, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\db\models\fields\__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <WSGIRequest: GET '/items/stk_push'>.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
ERROR:django.request:Internal Server Error: /items/1/
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 47, in detail
    return render(
           ^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 515, in parse
    self.unclosed_block_tag(parse_until)
  File "D:\Django\ecomvenv\Lib\site-packages\django\template\base.py", line 578, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 1: 'block'. Looking for one of: endblock.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /items/stk_push
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /items/stk_push
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /items/stk_push
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /items/stk_push
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: stk_push() takes 0 positional arguments but 1 was given
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 82, in stk_push
    LipaNaMpesaOnline.sendSTK(amount=1, phone_number="254792009556",orderId=0,transaction_id=None,shortcode=174379,account_number=None)
  File "D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py", line 52, in sendSTK
    s = code + PASS_KEY + time_now
        ~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'str'
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\settings.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 82, in stk_push
    LipaNaMpesaOnline.sendSTK(amount=1, phone_number="254792009556",orderId=0,transaction_id=None,shortcode=174379,account_number=None)
  File "D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py", line 52, in sendSTK
    s = code + PASS_KEY + time_now
        ~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'str'
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\settings.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\settings.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 82, in stk_push
    LipaNaMpesaOnline.sendSTK(amount=1, phone_number="254792009556",orderId=0,transaction_id=None,shortcode=174379,account_number=None)
  File "D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py", line 52, in sendSTK
    s = code + PASS_KEY + time_now
        ~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'str'
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 82, in stk_push
    LipaNaMpesaOnline.sendSTK(amount=1, phone_number="254792009556",orderId=0,transaction_id=None,shortcode=174379,account_number=None)
  File "D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py", line 53, in sendSTK
    encoded = b64encode(s.encode('utf-8')).decode('utf-8')
                        ^
NameError: name 's' is not defined
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\e_ticket_django\apps\event\views.py", line 82, in stk_push
    LipaNaMpesaOnline.sendSTK(amount=1, phone_number="254792009556",orderId=0,transaction_id=None,shortcode=174379,account_number=None)
  File "D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py", line 52, in sendSTK
    s = code + PASS_KEY + time_now
        ~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'str'
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\ecomvenv\Lib\site-packages\mpesa\LipaNaMpesaOnline.py changed, reloading.
ERROR:django.request:Internal Server Error: /items/stk_push
Traceback (most recent call last):
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "D:\Django\ecomvenv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view apps.event.views.stk_push didn't return an HttpResponse object. It returned None instead.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\event\views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /product/10
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\views.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
INFO:django.utils.autoreload:D:\Django\e_ticket_django\apps\core\urls.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
